// Centralized theme object for fashion-saga, modeled after fashion-theme-1
// Now reads dynamic overrides from config/appConfig.ts generated by the builder
import { APP_CONFIG } from '../config/appConfig';

export type Theme = {
  colors: {
    primary: string;
    background: string;
    text: string;
    subtitle: string;
    buttonText: string;
    link: string;
    logoBackground: string;
  };
  fonts: {
    regular: string;
    bold: string;
  };
  fontSizes: {
    title: number;
    subtitle: number;
    button: number;
    link: number;
  };
  spacing: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
  };
  borderRadius: {
    sm: number;
    md: number;
    lg: number;
  };
};

const defaults: Theme = {
  colors: {
    primary: '#156BFF',
    background: '#fff',
    text: '#222',
    subtitle: '#666',
    buttonText: '#fff',
    link: '#156BFF',
    logoBackground: '#F5F6FA',
  },
  fonts: {
    regular: 'System',
    bold: 'System',
  },
  fontSizes: {
    title: 36,
    subtitle: 16,
    button: 18,
    link: 15,
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 100,
  },
};

// Merge runtime theme colors if provided by builder
const runtimeColors = (APP_CONFIG?.theme as any)?.colors || {};
const storeBrandingColors = (APP_CONFIG?.store?.branding as any)?.colors || {};
const theme: Theme = {
  ...defaults,
  colors: {
    ...defaults.colors,
    ...runtimeColors,
    ...storeBrandingColors, // Store branding colors take precedence
  },
};

export default theme; 