// Enhanced centralized theme object for fashion-saga
// Now reads dynamic overrides from config/appConfig.ts generated by the builder
import { APP_CONFIG } from '../config/appConfig';

export type Theme = {
  colors: {
    // Primary colors
    primary: string;
    secondary: string;
    accent: string;
    
    // Background colors
    background: string;
    surface: string;
    card: string;
    
    // Text colors
    text: string;
    subtitle: string;
    buttonText: string;
    link: string;
    
    // Status colors
    success: string;
    warning: string;
    error: string;
    info: string;
    
    // UI colors
    border: string;
    divider: string;
    shadow: string;
    overlay: string;
    
    // Special colors
    logoBackground: string;
    flashSale: string;
    premium: string;
    discount: string;
    
    // Status-specific colors
    orderStatus: {
      pending: string;
      confirmed: string;
      processing: string;
      shipped: string;
      delivered: string;
      cancelled: string;
      returned: string;
    };
    
    paymentStatus: {
      pending: string;
      paid: string;
      failed: string;
      refunded: string;
    };
  };
  fonts: {
    regular: string;
    bold: string;
    medium: string;
    light: string;
  };
  fontSizes: {
    title: number;
    subtitle: number;
    button: number;
    link: number;
    caption: number;
    small: number;
  };
  spacing: {
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xxl: number;
  };
  borderRadius: {
    sm: number;
    md: number;
    lg: number;
    xl: number;
  };
  shadows: {
    small: {
      shadowColor: string;
      shadowOffset: { width: number; height: number };
      shadowOpacity: number;
      shadowRadius: number;
      elevation: number;
    };
    medium: {
      shadowColor: string;
      shadowOffset: { width: number; height: number };
      shadowOpacity: number;
      shadowRadius: number;
      elevation: number;
    };
    large: {
      shadowColor: string;
      shadowOffset: { width: number; height: number };
      shadowOpacity: number;
      shadowRadius: number;
      elevation: number;
    };
  };
};

const defaults: Theme = {
  colors: {
    // Primary colors
    primary: '#156BFF',
    secondary: '#111827',
    accent: '#FF6B6B',
    
    // Background colors
    background: '#fff',
    surface: '#f8f9fa',
    card: '#ffffff',
    
    // Text colors
    text: '#222',
    subtitle: '#666',
    buttonText: '#fff',
    link: '#156BFF',
    
    // Status colors
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    info: '#2196F3',
    
    // UI colors
    border: '#E0E0E0',
    divider: '#E0E0E0',
    shadow: '#000',
    overlay: 'rgba(0, 0, 0, 0.5)',
    
    // Special colors
    logoBackground: '#F5F6FA',
    flashSale: '#FF6B6B',
    premium: '#FFD700',
    discount: '#FF4444',
    
    // Status-specific colors
    orderStatus: {
      pending: '#FF9800',
      confirmed: '#2196F3',
      processing: '#9C27B0',
      shipped: '#3F51B5',
      delivered: '#4CAF50',
      cancelled: '#F44336',
      returned: '#FF5722',
    },
    
    paymentStatus: {
      pending: '#FF9800',
      paid: '#4CAF50',
      failed: '#F44336',
      refunded: '#9E9E9E',
    },
  },
  fonts: {
    regular: 'System',
    bold: 'System',
    medium: 'System',
    light: 'System',
  },
  fontSizes: {
    title: 36,
    subtitle: 16,
    button: 18,
    link: 15,
    caption: 12,
    small: 10,
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 100,
    xl: 20,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 12,
    },
  },
};

// Merge runtime theme colors if provided by builder
const runtimeColors = (APP_CONFIG?.theme as any)?.colors || {};
const storeBrandingColors = (APP_CONFIG?.store?.branding as any)?.colors || {};

// Create enhanced theme with all colors
const theme: Theme = {
  ...defaults,
  colors: {
    ...defaults.colors,
    ...runtimeColors,
    ...storeBrandingColors, // Store branding colors take precedence
    
    // Ensure status colors are properly set
    orderStatus: {
      ...defaults.colors.orderStatus,
      ...(runtimeColors.orderStatus || {}),
      ...(storeBrandingColors.orderStatus || {}),
    },
    
    paymentStatus: {
      ...defaults.colors.paymentStatus,
      ...(runtimeColors.paymentStatus || {}),
      ...(storeBrandingColors.paymentStatus || {}),
    },
  },
};

export default theme; 