/**
 * Runtime App Configuration - Auto-generated by StoresA2Z Builder
 * This file is automatically updated when theme configuration changes
 */

export const APP_CONFIG = {
  store: {
    id: '',
    name: 'Fashion Saga',
    description: 'Premium fashion e-commerce mobile app',
    branding: {
      colors: {
        primary: '#156BFF',
        secondary: '#111827',
        accent: '#F59E0B',
        success: '#10B981',
        warning: '#F59E0B',
        error: '#EF4444',
        background: '#FFFFFF',
        surface: '#F8FAFC',
        text: '#1F2937',
        textSecondary: '#6B7280',
        border: '#E5E7EB'
      },
      logo: {
        url: '',
        alt: 'Store Logo'
      }
    },
    products: [],
    categories: []
  },
  theme: {
    colors: {},
    typography: {},
    spacing: {},
    layout: {},
    features: {
      authentication: true,
      cart: true,
      wishlist: true,
      reviews: true,
      search: true,
      filters: true,
      notifications: true,
      pushNotifications: false
    },
    branding: {}
  },
  // Identifiers & Deep Links
  identifiers: {
    androidPackageName: 'com.storesa2z.fashionsaga',
    iosBundleId: 'com.storesa2z.fashionsaga',
    scheme: 'fashionsaga'
  },
  links: {
    appLinksDomains: [], // Android App Links
    associatedDomains: [] // iOS Associated Domains
  },
  // Permissions
  permissions: {
    camera: true,
    photos: true,
    files: false,
    location: false,
    notifications: true
  },
  // Analytics Configuration
  analytics: {
    enableGA4: false,
    enableSentry: false,
    ga4Id: '',
    sentryDsn: '',
    facebookAppId: '',
    segmentKey: '',
    mixpanelKey: ''
  },
  // Push Notifications
  push: {
    android: {
      enable: true,
      topicOrders: true,
      topicPromotions: false
    },
    apns: {
      keyId: '',
      teamId: '',
      bundleId: '',
      p8Present: false
    },
    googleServicesPresent: false
  },
  // Notification Channels
  notifications: {
    channelName: 'General',
    channelDesc: 'General app notifications',
    importance: 'default' as 'min' | 'low' | 'default' | 'high'
  },
  // Legal & Store Listing
  legal: {
    privacyUrl: '',
    termsUrl: '',
    supportEmail: ''
  },
  listing: {
    shortDesc: '',
    fullDesc: '',
    category: '',
    contentRating: ''
  },
  // Localization
  locale: {
    primaryLang: 'en',
    localizedNames: {}
  },
  // Custom Fonts
  fonts: [] as Array<{
    familyName: string;
    url: string;
    weight?: number;
    style?: 'normal' | 'italic';
  }>
};

export default APP_CONFIG;
