/**
 * Live App Configuration - Auto-generated by StoresA2Z Preview Service
 * This file is automatically updated when theme configuration changes
 */

export const APP_CONFIG = {
  store: {
    id: '',
    name: '',
    description: '',
    branding: {},
    products: [],
    categories: []
  },
  theme: {
    colors: {},
    typography: {},
    spacing: {},
    layout: {},
    features: {},
    branding: {}
  }
};

export default APP_CONFIG; 