// /**
//  * Live App Configuration - Auto-generated by StoresA2Z Preview Service
//  * This file is automatically updated when theme configuration changes
//  */

// export const APP_CONFIG = {
//   store: {
//     id: '',
//     name: '',
//     description: '',
//     branding: {},
//     products: [],
//     categories: []
//   },
//   theme: {
//     colors: {},
//     typography: {},
//     spacing: {},
//     layout: {},
//     features: {},
//     branding: {}
//   }
// };

// export default APP_CONFIG; 

export const APP_CONFIG = {
  "store": {
    "id": "689d9c9f45e7baf29bfc4f4d",
    "name": "StoresA2Z Demo",
    "description": "",
    "branding": {
      "logo": "https://storesa2z.blr1.cdn.digitaloceanspaces.com/stores/689d9c9f45e7baf29bfc4f4d/icon.png",
      "colors": {
        "primary": "#eb2424",
        "secondary": "#111827"
      },
      "appName": "StoresA2Z Demo"
    },
    "products": [],
    "categories": []
  },
  "theme": {
    "colors": {
      "primary": "#eb2424",
      "secondary": "#111827"
    },
    "branding": {
      "logo": "https://storesa2z.blr1.cdn.digitaloceanspaces.com/stores/689d9c9f45e7baf29bfc4f4d/icon.png",
      "appName": "StoresA2Z Demo",
      "fontFamily": "System"
    }
  },
  "features": {},
  "branding": {
    "logo": "https://storesa2z.blr1.cdn.digitaloceanspaces.com/stores/689d9c9f45e7baf29bfc4f4d/icon.png",
    "colors": {
      "primary": "#eb2424",
      "secondary": "#111827"
    },
    "appName": "StoresA2Z Demo"
  },
  "fonts": [],
  // NEW: App Request specific configurations
  "appRequest": {
    "identifiers": {
      "androidPackageName": "",
      "iosBundleId": ""
    },
    "icons": {
      "appIconUrl": "",
      "adaptiveForegroundUrl": "",
      "adaptiveBackgroundColor": ""
    },
    "splash": {
      "imageUrl": "",
      "backgroundColor": "",
      "resizeMode": "contain" as "contain" | "cover",
      "darkImageUrl": "",
      "darkBackgroundColor": ""
    },
    "fonts": [] as Array<{
      "familyName": string;
      "url": string;
      "weight": number;
      "style": "normal" | "italic";
    }>,
    "permissions": {
      "camera": false,
      "photos": false,
      "files": false,
      "location": false,
      "notifications": false
    },
    "analytics": {
      "ga4Id": "",
      "sentryDsn": ""
    },
    "push": {
      "fcmServerKey": "",
      "android": {
        "enable": false,
        "topicOrders": false,
        "topicPromotions": false
      },
      "apns": {
        "keyId": "",
        "teamId": "",
        "bundleId": "",
        "p8Url": ""
      }
    }
  }
};

export default APP_CONFIG;
